from .soluciones_de_ecuaciones_de_una_variable.bisec import metodo_biseccion, encontrar_intervalo
from .soluciones_de_ecuaciones_de_una_variable.newton_v2 import metodo_newton_v2
from .soluciones_de_ecuaciones_de_una_variable.secante_v2 import metodo_secante_v2
from .soluciones_de_ecuaciones_de_una_variable.newton import metodo_newton
from .soluciones_de_ecuaciones_de_una_variable.secante import metodo_secante
from .soluciones_de_ecuaciones_de_una_variable.pto_fijo import metodo_punto_fijo



